config/routes.rb
Rails.application.routes.draw do
  get 'authentications/home'
  resources :users
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/signup',      to: 'users#new', as: 'signup'
  root 'authentications#home'
  resources :posts 
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  accepts_nested_attributes_for :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :remember_tokenn, :activation_token
  has_many :posts
  accepts_nested_attributes_for :posts

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 3 }

  def self.digest(_string)
    if ActiveModel::SecurePassword.min_cost
      BCrypt::Engine::MIN_COST
    else
      BCrypt::Engine.cost
    end
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_tokenn = User.new_token
    update_attribute(:remember_token, User.digest(remember_tokenn))
  end

  def authenticated?(remember_tokenn)
    return false if remember_token.nil?

    BCrypt::Password.new(remember_token).is_password?(remember_tokenn)
  end

  def forget
    update_attribute(:remember_token, nil)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/authentications_controller.rb
# frozen_string_literal: true

class AuthenticationsController < ApplicationController
  def home; end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :logged_in_user, only: %i[new create edit]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path
    else
      flash.now[:danger] = 'Post was not created'
      render 'new'
    end
  end

  def show; end

  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = 'User deleted'
    redirect_to posts_path
  end

  private

  def logged_in_user
    return if logged_in?

    store_location
    flash[:danger] = 'Please log in.'
    redirect_to login_url
  end

  def set_user
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:name, :content)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to posts_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.all
  end

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)
    log_in @user
    remember @user
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/authentications_helper.rb
# frozen_string_literal: true

module AuthenticationsHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_tokenn] = user.remember_tokenn
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user&.authenticated?(cookies[:remember_tokenn])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_tokenn)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/authentications/home.html.erb
<div class="container">
    <div class="center jumbotron">
    <h1>Welcome to the Authentication App</h1>

    <h2>
        This is the home page for the Authentication with Ruby on Rails.
    </h2>

    <div class="col-12 text-center">
      <%= link_to "Secret Post App", root_path, class: "btn btn-lg btn-primary" %>
    </div>
   

</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Secret Post App</a>
    </div>

    <form class="form-inline">
    <% if logged_in? %>

      <a class="btn btn-outline-primary disabled" href="/posts" role="button">
        Hi <%= current_user.name %>
      </a>
      <div style="padding-left: 10px;">

        <%= link_to "Log out", logout_path, method: :delete , :class => "btn btn-outline-danger"%>
      </div>
    <% else%>

      <a class="btn btn-outline-primary" href="/login" role="button">
      Login
      </a>
      <div style="padding-left: 10px;">
        <a class="btn btn-outline-success" href="/users/new " role="button">
        Sign Up
        </a>
      </div>
    <% end %>

    </form>
  </div>
</nav>

app/views/layouts/_rails.default.html.erb
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
   
   
  

app/views/layouts/_rails_default.html.erb
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
   
   
  

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authapp</title>
      <%= render 'layouts/rails_default'%>
      <%= render 'layouts/shim' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    
  </body>
</html>

app/views/posts/_form.html.erb
 <div class="col-2 col-lg-d-none"></div>
    <div class="col-8 col-md-offset-3">
      <%= form_with scope: :post, url: posts_path, local: true do |f| %>

        <%= f.label :name %>

        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :content %>
        
        <%= f.text_field :content, class: 'form-control' %>

        <div class="col-12 text-center">

          <%= f.submit "Create Post", class: "btn btn-primary mt-3" %>

        </div>
        
      <% end %>
    </div>

app/views/posts/edit.html.erb
<% provide(:title, "Edit Post") %>
<div class="container">
  <div class="row">
    <div class="col-12 text-center mt-4">
      <h1>Edit Post</h1>
    </div>

    <%= render 'form', post: @post %>
  </div>

</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-12 text-center mt-4">
      <h1>Posts</h1>
    </div>
    <div class="col-12 text-center mt-4">
      <% if logged_in? %>
        <h4>Hi <%= current_user.name %></h4>
      <% end %>
    </div>

    
    <table class="table col-12 text-center">
      <thead class="thead-dark">
      
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Content</th>
          <% if logged_in? %>
            <th>Author</th>
          <% end %>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= post.name %></td>
            <td><%= post.content %></td>
            <% if logged_in? %>
              <td><%= post.user.name %></td>
            <% end %>
            <td><%= link_to 'Show', post %></td>
            <% if current_user == post.user %>
              <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
    <div class="col-12 text-center">
    <%= link_to 'New Post', new_post_path, class: "btn btn-primary mt-3" %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<% provide(:title, "Create Post") %>
<div class="container">
  <div class="row">
    <div class="col-12 text-center mt-4">
      <h1>Create Post</h1>
    </div>

    <%= render 'form', post: @post %>
  </div>

</div>

app/views/users/_form.html.erb
<div class="col-2 col-lg-d-none"></div>
    <div class="col-8 col-md-offset-3">
    <%= form_with(model: user, local: true , :class => "form") do |form| %>
      <% if user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group text-left">
        <%= form.label :name %>
        <%= form.text_field :name , :class => "form-control"%>
      </div>

      <div class="form-group text-left">
        <%= form.label :email %>
        <%= form.text_field :email , :class => "form-control"%>
      </div>

      <div class="form-group text-left">
        <%= form.label :password %>
        <%= form.text_field :password, :class => "form-control" %>
      </div>

      <div class="actions">
        <%= form.submit :class => "btn btn-success mt-2"%>
      </div>
    <% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-12 text-center mt-4">
      <h1>Users</h1>
    </div>

    <table class="table col-12 text-center">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Password</th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.password %></td>
            <td><%= link_to 'Show', user %></td>
            <% if current_user == user %>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
  </div>
  <div class="col-12 text-center">
    <%= link_to 'New User', new_user_path, class: "btn btn-primary mt-3" %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<div class="container">
    <div class="row">
        <div class="col-12 text-center mt-4">
            <h1>New User</h1>

        </div>
        <div class="col-2 col-lg-d-none"></div>

        <div class="col-8 text-center">

            <%= render 'form', user: @user %>
        </div>
        <div class="col-2 col-lg-d-none"></div>

        
        <div class="col-12 text-center mt-5">
            <div class="footer text-center bg-light pt-3 pb-3">
            <%= link_to 'Back', users_path , :class => "btn btn-outline-secondary"%>

            </div>
        </div>

        

    </div>

</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <p>
    <strong>Name:</strong>
    <%= @user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>
  <%= link_to 'Back', users_path %> |
  <%= link_to 'Posts', posts_path %> |
  <%= link_to 'New', new_post_path %>
</div>